#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
# Capacitor shell for the Creator Rig (CW-01.9): the Apple-side steps only a
# human can do. Run from the repo root: scripts/capacitor-wizard.sh
# Values land in .env.capacitor (never committed) and in ios/App/App/App.entitlements.

ENV_FILE=".env.capacitor"
TOTAL_STAGES=9
BUNDLE_ID="com.surfscore.kodable.creatorrig"
TEAM_ID="SG83N65WAM"
PRODUCT_ID="${BUNDLE_ID}.coin"
MAC_IP="$(ipconfig getifaddr en0 2>/dev/null || echo '<mac-ip>')"

banner "Creator Rig: Capacitor shell on the iPad and iPhone"

# ── 0 ─────────────────────────────────────────────────────────────────────
stage "Xcode: install the iOS platform component"
say "Xcode 26.6 on this Mac has no iOS 26.5 platform installed; xcodebuild refuses every iOS destination until it is."
step "Either: Xcode > Settings > Components > iOS 26.5 > download (several GB)."
step "Or in a terminal: xcodebuild -downloadPlatform iOS"
step "Then check: cd ios/App && xcodebuild -project App.xcodeproj -scheme App -destination 'generic/platform=iOS Simulator' CODE_SIGNING_ALLOWED=NO build   → BUILD SUCCEEDED"
pause "Platform installed and the simulator build succeeded? Press Enter."

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Xcode: sign the app with the Kodable team"
say "The iOS project is generated. Xcode registers the rig's App ID with automatic signing."
step "Run: npx cap open ios   (or open ios/App/App.xcodeproj)"
step "Select the App target > Signing & Capabilities."
step "Team: Kodable (${TEAM_ID}). Signing: Automatic. Bundle Identifier: ${BUNDLE_ID}."
note "Xcode creates the App ID and a development profile. If it asks, sign in with the Apple ID on the Kodable team."
step "Capability 'Associated Domains' should already be listed (from App.entitlements). Leave the HOST entry for stage 5."
pause "Signing shows no red errors? Press Enter."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Run the shell on the iPad, loading the Mac's dev server"
say "Live mode: the app loads http://${MAC_IP}:5173 so web changes need no app rebuild, and the report collector is same-origin."
step "In a terminal in the repo: npm run dev        (leave it running)"
step "In another: CAP_SERVER_URL=http://${MAC_IP}:5173 npx cap sync ios"
step "Connect the iPad by USB, unlock it, tap Trust. In Xcode pick the iPad as the run destination and press Run."
step "Keep 'npm run dev' running the whole time: the app loads the Mac's server on every launch and shows an empty screen when it is off."
step "First launch on the device: allow 'Local Network' when the app asks (Settings > Privacy & Security > Local Network > Creator Rig if you missed it). No entry appears under VPN & Device Management with the team profile; that is normal."
step "The rig index appears in the app. The device tag reads capacitor-ipad. Run 'baseline 200' and confirm the report says device=capacitor-ipad."
pause "Report seen with device=capacitor-ipad? Press Enter."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "App Store Connect: app record and the sandbox consumable"
say "The purchase scenario buys one consumable. It needs an app record and a product; nothing is submitted for review."
open_url "https://appstoreconnect.apple.com/apps"
step "Apps > + > New App: platform iOS, name 'Kodable Creator Rig' (any unique name), primary language English, Bundle ID ${BUNDLE_ID}, SKU creator-rig."
step "In the app: Monetization > In-App Purchases > + > Consumable. Reference name 'Test coin', Product ID: ${PRODUCT_ID}."
step "Add one price (lowest tier) and one localization (display name 'Test coin', description 'Rig test purchase'). Save. Status 'Ready to Submit' or 'Missing Metadata' both work in sandbox."
open_url "https://appstoreconnect.apple.com/business"
step "Agreements: the Paid Apps agreement must be Active, or sandbox purchases fail with an error about agreements."
ask IAP_PRODUCT_ID "Product ID as saved (Enter for ${PRODUCT_ID}):"
write_env IAP_PRODUCT_ID "${IAP_PRODUCT_ID:-$PRODUCT_ID}"
pause "Product saved? Press Enter."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Sandbox tester on the iPad"
open_url "https://appstoreconnect.apple.com/access/users/sandbox"
step "Sandbox > Testers > +. Use an email that is not an existing Apple account (a plus-address like you+rig@kodable.com works). Note the password."
step "On the iPad: Settings > App Store > Sandbox Account (bottom) > sign in with that tester."
ask SANDBOX_TESTER_EMAIL "Sandbox tester email:"
write_env SANDBOX_TESTER_EMAIL "$SANDBOX_TESTER_EMAIL"
step "In the shell: open 'purchase · coin', tap 'Buy the test coin'. Complete the sandbox sheet with the tester password."
step "The report shows transactionId and receipt sizes; Xcode's console prints RIG_RECEIPT. Send the report to the collector."
pause "Purchase completed? Press Enter."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Universal Link: choose the host and publish the AASA file"
say "iOS fetches https://HOST/.well-known/apple-app-site-association from the domain ROOT. kodable.github.io has no site at its root, so GitHub Pages cannot host it."
say "Options: (a) a Netlify site for the rig (deploy dist/ with public/.well-known at the root), or (b) add the rig's entry to the AASA that game.kodable.com already serves (KodableWebGame/static/.well-known/apple-app-site-association) and deploy it."
note "The JSON to publish is public/.well-known/apple-app-site-association (appID ${TEAM_ID}.${BUNDLE_ID}, paths /creator-rig and /creator-rig/*)."
ask UL_HOST "Host that serves the AASA at its root (for example creator-rig.netlify.app or game.kodable.com):"
write_env UL_HOST "$UL_HOST"
if [[ -n "$UL_HOST" ]]; then
  sed -i '' "s|applinks:[^<]*|applinks:${UL_HOST}?mode=developer|" ios/App/App/App.entitlements
  printf '  %s✓ wrote%s applinks:%s?mode=developer → ios/App/App/App.entitlements\n' "$GREEN" "$RESET" "$UL_HOST"
  step "Check the file is live: curl -sI https://${UL_HOST}/.well-known/apple-app-site-association   (200, JSON, no redirect)"
fi
step "On the iPad: Settings > Developer > Associated Domains Development: on (developer mode skips Apple's CDN cache)."
pause "AASA reachable and the switch on? Press Enter."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Universal Link: rebuild and tap a link"
step "In Xcode: Run again (the entitlement changed)."
step "On the iPad, paste this into Notes and long-press it: https://${UL_HOST:-HOST}/creator-rig/?scenario=bodies&adapter=box2d&count=200"
step "Choose 'Open in Creator Rig'. The shell must open the bodies scenario; its report carries via=universal-link."
note "If Safari opens instead: the AASA is not served from the root, has a redirect, or the app was not reinstalled after the entitlement change."
pause "Shell opened the scenario from the link? Press Enter."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Shell checks: silent switch, text input, jettison"
step "audio · tap with the iPad's ring/silent switch OFF: the beep must be audible (AVAudioSession playback category in AppDelegate)."
step "textinput · field: tap the field, type, tap the canvas. Pass: keyboard height reported, canvas size unchanged, dismissal counted."
warn "jettison · 32mb allocates memory until iOS kills the web content process. Do it last. The shell reloads the view; the scenario then reports recovered=true and the MB at death."
step "Send each report to the collector, or Share them to the Mac."
pause "Reports sent? Press Enter."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Same on the iPhone, then the bundled build"
step "Repeat stages 2, 4 (sign in the tester), 6 and 7 on the iPhone."
step "Bundled build (no dev server): npm run build && npx cap sync ios   (CAP_SERVER_URL unset), then Run. Set the Collector field on the index page to http://${MAC_IP}:5173 so Send works from the app's own origin."
step "In the rig folder: npm run results   prints the tables with the capacitor-ipad and capacitor-iphone rows."
pause "Done? Press Enter."

finish
